package main

import (
	"testing"
)

// CanonicalEndpointCount is the source-of-truth canonical
// endpoint count for the OSS api-docgen catalog. It is the same
// number the operator gets from the canonical shell command:
//
//	go run ./tools/api-docgen --dry-run \
//	  >/tmp/idp-oss-api-docgen.yaml && \
//	grep -c '^  - id:' /tmp/idp-oss-api-docgen.yaml
//
// History (preserved here as documentation since the test below
// asserts the CURRENT number only):
//
//	138 — pre-2026-06-13 count before the appliance setup
//	      foundation slice
//	      `agent-a-20260613-idp-oss-ui-appliance-setup-foundation`
//	      added the three /api/setup/* routes.
//	141 — count after the +3 setup endpoints landed.
//	132 — current count after the SCIM v2 surface (9 endpoints) was
//	      removed from OSS to close a licensing leak (SCIM 2.0 is
//	      Enterprise/CE-only). See
//	      docs/audit/changelog/scim-oss-leak-removal.md.
//
// Update discipline: bump this constant + update the wiki
// references (wiki/repos/identuum-idp-oss.md frontmatter +
// validated-code-status table + wiki/validation/identuum-go.md
// §C + wiki/index.md row for repos/identuum-idp-oss.md) IN THE
// SAME SLICE that adds/removes routes. The
// TestGeneratedOutputMatchesGoldenFixture test in verify_test.go
// will also fire if the golden YAML fixture isn't regenerated;
// this canonical-count test is the secondary canary that pins
// the number in plain Go so a route-count drift surfaces with
// a human-readable failure message.
//
// Why a separate test from TestGeneratedOutputMatchesGoldenFixture?
// The golden-fixture test pins the EXACT generated bytes — useful
// for catching annotation reshape (summary edit, parameter
// reorder), but its failure message says "got N bytes, want M
// bytes" which doesn't tell the operator what to do next when a
// real route count change is intentional. THIS test fails with a
// targeted message naming the canonical wiki + docs files that
// must also be updated.
// 132 → 131: the dead site_admin POST /api/v1/organizations/activate
// stub was retired (Option A; docs/audit/release-readiness/org-activate-retire-decision.md).
// 131 → 130: GET /metrics was un-registered from the public API
// router — it now serves on its own, separate, internal-only
// listener (internal/runtime.Runtime.startMetricsListener) instead,
// closing the tenant/IDP-enumeration exposure noted in
// docs/audit/changelog/security-headers-middleware.md. See
// docs/audit/changelog/metrics-separate-listener.md.
// 130 → 124: the six advertised-but-unwired advanced-DCR routes
// (GET/POST /api/v1/dcr/initial-access-tokens, POST .../:id/revoke,
// GET/PUT/DELETE /api/v1/oauth/register/:client_id) were removed from
// the OSS surface — their backing services were never constructed by
// the runtime so they could only 404, and advanced DCR is
// Enterprise/CE-only (integrity-audit F6/C1; see
// docs/audit/changelog/dcr-surface-scoping.md). Basic RFC 7591
// POST /api/v1/oauth/register remains served.
// 124 → 128: added the org-admin OIDC-provider config API — POST/GET/PUT/DELETE
// /api/v1/organizations/:id/identity-provider — the first count-changing slice
// of OSS basic single-provider upstream OIDC login (org_admin own-org only;
// site_admin does not manage tenant IdPs; one oidc provider per org).
// See docs/audit/changelog/oidc-login-slice2-config-api.md.
// 128 → 129: added the upstream-OIDC login-initiation route
// GET /api/v1/auth/idp/:id/login (public) — OSS basic single-provider login
// Slice 4. Resolves the org's ONE oidc provider by id, fetches discovery,
// mints state/nonce/PKCE, persists OIDCState, and 302-redirects to the
// provider's authorize URL. See docs/audit/changelog/oidc-login-slice4-initiation.md.
// 129 → 130: added the upstream-OIDC callback route
// GET /api/v1/auth/idp/:id/callback (public) — OSS basic single-provider login
// Slice 5. Consumes the one-time state, exchanges the code, and strictly
// validates the ID token against the provider JWKS → validated ExternalUser.
// See docs/audit/changelog/oidc-login-slice5-callback-validation.md.
// 130 → 131: added the audit-log read route GET /api/v1/audit/events
// (site_admin unscoped OR org_admin own-org with audit:read) — the L-2
// read half over the audit_events table.
const CanonicalEndpointCount = 132

// TestCanonicalEndpointCount asserts the canonical OSS endpoint
// count via the in-process api-docgen extraction path — the same
// path the operator-facing `go run ./tools/api-docgen --dry-run`
// command uses. The test is source-derived (not a static golden
// byte comparison) so it asserts the LIVE count under the current
// source tree, not a cached fixture. Pairs with the wiki source-
// of-truth: wiki/repos/identuum-idp-oss.md (Endpoint count: 141),
// wiki/validation/identuum-go.md §C (Expected result: 141), and
// wiki/index.md two rows that document the same number.
//
// IMPORTANT: this test asserts the api-docgen-derived canonical
// count, NOT a gograph-routes count. `gograph routes` lists every
// http.HandleFunc / mux.Handle the analyzer detects across
// production + test source — it is consistently higher than the
// product-surface count because test fixtures and dev-only routes
// inflate it. The canonical product endpoint count is exclusively
// the api-docgen output (per wiki/validation/identuum-go.md §C +
// wiki/agent-rules.md). Operators MUST NOT substitute the gograph
// number into this slot.
func TestCanonicalEndpointCount(t *testing.T) {
	roots, err := defaultSourceRoots()
	if err != nil {
		t.Fatalf("defaultSourceRoots: %v (cannot verify canonical endpoint count without source roots)", err)
	}
	endpoints, err := EndpointsFromAnnotations(roots)
	if err != nil {
		t.Fatalf("EndpointsFromAnnotations: %v (extraction failure prevents canonical endpoint count check)", err)
	}
	if got := len(endpoints); got != CanonicalEndpointCount {
		t.Fatalf(
			"OSS api-docgen canonical endpoint count drift: extracted %d endpoints, want %d.\n\n"+
				"This count is the SOURCE OF TRUTH — if the change is intentional, update IN THE SAME SLICE:\n"+
				"  1. The CanonicalEndpointCount constant in tools/api-docgen/canonical_count_test.go (this file).\n"+
				"  2. tools/api-docgen/testdata/endpoints.golden.yaml + endpoints.manifest.txt — regenerate via:\n"+
				"       go run ./tools/api-docgen --output tools/api-docgen/testdata/ && \\\n"+
				"       mv tools/api-docgen/testdata/endpoints.yaml tools/api-docgen/testdata/endpoints.golden.yaml\n"+
				"  3. wiki/repos/identuum-idp-oss.md — every 'Endpoint count: %d' / 'Expected result: %d' / validated-code-status table entry.\n"+
				"  4. wiki/validation/identuum-go.md §C — 'Expected result: **%d**' line.\n"+
				"  5. wiki/index.md — two rows that reference the count in the description column.\n"+
				"  6. AGENTS.md (if present at the OSS repo root) — 'Expected: `%d`' line.\n\n"+
				"DO NOT silently bump the constant without performing steps 2-6 in the SAME slice — the wiki + docs are the operator-facing source of truth.",
			got, CanonicalEndpointCount,
			CanonicalEndpointCount, CanonicalEndpointCount, CanonicalEndpointCount, CanonicalEndpointCount,
		)
	}
}

// TestCanonicalEndpointCount_SetupFoundationRoutesPresent pins
// that the three appliance setup-foundation routes added by
// slice `agent-a-20260613-idp-oss-ui-appliance-setup-foundation`
// are present in the extracted endpoint set. These three routes
// account for the 138 → 141 delta the canonical count records.
// If any of them disappears from the source tree without an
// accompanying CanonicalEndpointCount decrement, this test
// surfaces the omission BEFORE the count test below would fail
// with a less-targeted message.
func TestCanonicalEndpointCount_SetupFoundationRoutesPresent(t *testing.T) {
	roots, err := defaultSourceRoots()
	if err != nil {
		t.Fatalf("defaultSourceRoots: %v", err)
	}
	endpoints, err := EndpointsFromAnnotations(roots)
	if err != nil {
		t.Fatalf("EndpointsFromAnnotations: %v", err)
	}
	// Build a (method, path) lookup so the assertions read clearly.
	type key struct{ method, path string }
	seen := make(map[key]bool, len(endpoints))
	for _, e := range endpoints {
		seen[key{e.Method, e.Path}] = true
	}
	required := []key{
		{"GET", "/api/setup/status"},
		{"POST", "/api/setup/verify-token"},
		{"POST", "/api/setup/complete"},
	}
	for _, want := range required {
		if !seen[want] {
			t.Errorf("appliance setup-foundation route %s %s is MISSING from the api-docgen output — was it removed without updating CanonicalEndpointCount? See wiki/repos/identuum-idp-oss.md §'Setup foundation (partial — 2026-06-13)'.",
				want.method, want.path)
		}
	}
}
