package main

import (
	"bufio"
	"fmt"
	"io"
	"sort"
)

// generate sorts endpoints into the canonical (module, surface, path,
// method) order and writes a deterministic YAML representation to w.
// Two invocations on the same input produce byte-identical output.
// The function does not consult the system clock or any environment
// state.
func generate(w io.Writer, endpoints []Endpoint) error {
	sorted := make([]Endpoint, len(endpoints))
	copy(sorted, endpoints)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].Module != sorted[j].Module {
			return sorted[i].Module < sorted[j].Module
		}
		if sorted[i].Surface != sorted[j].Surface {
			return sorted[i].Surface < sorted[j].Surface
		}
		if sorted[i].Path != sorted[j].Path {
			return sorted[i].Path < sorted[j].Path
		}
		if sorted[i].Method != sorted[j].Method {
			return sorted[i].Method < sorted[j].Method
		}
		return sorted[i].ID < sorted[j].ID
	})

	bw := bufio.NewWriter(w)
	const header = "# Generated by identuum-idp-oss/tools/api-docgen (Phase P3 — annotation-driven; endpoints only).\n" +
		"# Do not hand-edit. To update, edit the // docgen: block above the relevant route registration and re-run the generator.\n" +
		"endpoints:\n"
	if _, err := bw.WriteString(header); err != nil {
		return err
	}
	for i := range sorted {
		if err := writeEndpoint(bw, &sorted[i]); err != nil {
			return fmt.Errorf("write endpoint %s: %w", sorted[i].ID, err)
		}
	}
	return bw.Flush()
}

func writeEndpoint(bw *bufio.Writer, e *Endpoint) error {
	lines := [...]struct {
		key, value string
	}{
		{"id", e.ID},
		{"module", e.Module},
		{"surface", e.Surface},
		{"method", e.Method},
		{"path", e.Path},
		{"handler", e.Handler},
		{"registrar", e.Registrar},
		{"summary", e.Summary},
		{"tier", e.Tier},
		{"auth", e.Auth},
		{"request_schema", e.RequestSchema},
		{"response_schema", e.ResponseSchema},
		{"source_package", e.SourcePackage},
		{"source_symbol", e.SourceSymbol},
	}
	first := true
	for _, l := range lines {
		prefix := "    "
		if first {
			prefix = "  - "
			first = false
		}
		if _, err := bw.WriteString(prefix); err != nil {
			return err
		}
		if _, err := bw.WriteString(l.key); err != nil {
			return err
		}
		if _, err := bw.WriteString(": "); err != nil {
			return err
		}
		if _, err := bw.WriteString(yamlScalar(l.value)); err != nil {
			return err
		}
		if err := bw.WriteByte('\n'); err != nil {
			return err
		}
	}
	if _, err := bw.WriteString("    deferred: "); err != nil {
		return err
	}
	if e.Deferred {
		if _, err := bw.WriteString("true\n"); err != nil {
			return err
		}
	} else {
		if _, err := bw.WriteString("false\n"); err != nil {
			return err
		}
	}
	// feature_gate is emitted ONLY when non-empty so endpoints with
	// no gate annotation produce no extra line. This keeps the
	// golden YAML diff small for the 90+ legacy endpoints that
	// pre-date the feature_gate annotation.
	if e.FeatureGate != "" {
		if _, err := bw.WriteString("    feature_gate: "); err != nil {
			return err
		}
		if _, err := bw.WriteString(yamlScalar(e.FeatureGate)); err != nil {
			return err
		}
		if err := bw.WriteByte('\n'); err != nil {
			return err
		}
	}
	return nil
}

// yamlScalar produces a YAML-safe scalar for a string. Empty strings
// are emitted as the unquoted YAML empty value (renders to null) so
// the docs consumer can distinguish "unknown" from "empty string"
// when needed. All other strings are double-quoted with JSON-style
// escaping (which YAML 1.2 double-quoted form accepts verbatim).
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	out := make([]byte, 0, len(s)+2)
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '\\':
			out = append(out, '\\', '\\')
		case '"':
			out = append(out, '\\', '"')
		case '\n':
			out = append(out, '\\', 'n')
		case '\r':
			out = append(out, '\\', 'r')
		case '\t':
			out = append(out, '\\', 't')
		default:
			if c < 0x20 {
				// Drop control bytes; they should not appear in our
				// curated metadata. Emitting them would make the
				// output less deterministic across YAML parsers.
				continue
			}
			out = append(out, c)
		}
	}
	out = append(out, '"')
	return string(out)
}
