package main

import (
	"bufio"
	"bytes"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// TestOpenAPI_CheckedInSpecIsCurrent — the repo-root openapi.yaml, the public
// machine-readable API surface for OSS consumers, must be byte-for-byte what
// the generator emits from the source tree NOW.
//
// THE-UNGUARDED-SPEC (2026-09-06). Until this test nothing in `make verify`
// compared the checked-in file with the generator: the golden fixture pins
// the generator against ITSELF (testdata/endpoints.golden.yaml), and the
// checked-in spec was pinned by nothing. Measured: a whole endpoint — GET
// /api/v1/agent-communication-authorizations — was absent from openapi.yaml
// while the generator counted 144 and every gate stayed green; and a path
// renamed by hand in the checked-in file left `make verify` green (27
// targets, exit 0) at 6d1cc92.
//
// The generator is byte-deterministic (TestOpenAPI_Deterministic; three CLI
// runs measured identical), so an exact comparison is not a flake. This test
// regenerates IN MEMORY through the same `run` the CLI uses (--dry-run writes
// the identical bytes to stdout that --output writes to disk) and NEVER writes
// the file it judges: the fix is a command the operator runs, named in the
// failure.
//
// RULE: OPENAPI-CHECKED-IN-CURRENT-1
func TestOpenAPI_CheckedInSpecIsCurrent(t *testing.T) {
	var generated, errBuf bytes.Buffer
	if code := run([]string{"--dry-run", "--format=openapi"}, &generated, &errBuf); code != 0 {
		t.Fatalf("api-docgen --dry-run --format=openapi: exit %d, stderr=%s", code, errBuf.String())
	}
	checkedInPath := filepath.Join("..", "..", "openapi.yaml")
	checkedIn, err := os.ReadFile(checkedInPath)
	if err != nil {
		t.Fatalf("read the checked-in %s: %v", checkedInPath, err)
	}
	if bytes.Equal(generated.Bytes(), checkedIn) {
		return
	}

	genPaths := openAPIPathKeys(generated.Bytes())
	cinPaths := openAPIPathKeys(checkedIn)
	onlyGenerated := setDifference(genPaths, cinPaths)
	onlyCheckedIn := setDifference(cinPaths, genPaths)
	lineNo, genLine, cinLine := firstDifferingLine(generated.Bytes(), checkedIn)

	t.Fatalf("the checked-in ./openapi.yaml is NOT what the generator emits (%d generated bytes vs %d checked in):\n"+
		"  paths only in the generator:      %v\n"+
		"  paths only in the checked-in file: %v\n"+
		"  first differing line %d:\n"+
		"    generated:  %q\n"+
		"    checked-in: %q\n"+
		"  fix: make api-docs   (regenerates ./openapi.yaml from the source tree; this test never writes it)",
		generated.Len(), len(checkedIn), onlyGenerated, onlyCheckedIn, lineNo, genLine, cinLine)
}

// openAPIPathKeys returns the path keys of the emitted document: the lines
// shaped `  "/…":` (two-space indent, quoted path, colon), which is how the
// emitter writes every entry under `paths:`.
func openAPIPathKeys(doc []byte) map[string]bool {
	keys := map[string]bool{}
	sc := bufio.NewScanner(bytes.NewReader(doc))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, `  "/`) && strings.HasSuffix(line, `":`) {
			keys[strings.TrimSuffix(strings.TrimPrefix(line, `  "`), `":`)] = true
		}
	}
	return keys
}

func setDifference(a, b map[string]bool) []string {
	var out []string
	for k := range a {
		if !b[k] {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

// firstDifferingLine reports the 1-based line number at which the two
// documents first disagree, with both lines ("" past the shorter one).
func firstDifferingLine(a, b []byte) (int, string, string) {
	la := strings.Split(string(a), "\n")
	lb := strings.Split(string(b), "\n")
	n := len(la)
	if len(lb) > n {
		n = len(lb)
	}
	for i := 0; i < n; i++ {
		var x, y string
		if i < len(la) {
			x = la[i]
		}
		if i < len(lb) {
			y = lb[i]
		}
		if x != y {
			return i + 1, x, y
		}
	}
	return 0, "", ""
}
