package main

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strings"
)

// generateOpenAPI maps the SAME []Endpoint records the YAML emitter
// (generate, in emit.go) consumes into a deterministic OpenAPI 3.0.3
// document, hand-written in YAML (no new go.mod dependency — the same
// house style as emit.go's yamlScalar-based writer).
//
// Deliberately NOT modeled: request/response BODY field schemas. The
// Endpoint record carries only a schema NAME (e.g.
// "oss.handlers.safeOrganization"), never field-level shape. Inventing
// field schemas from a name would be fabrication; instead each named
// response schema becomes a generic `type: object` placeholder
// component that documents the Go symbol it corresponds to, without
// claiming to model its fields.
//
// Two invocations on the same input produce byte-identical output —
// same sort discipline and no-timestamps rule as generate().
func generateOpenAPI(w io.Writer, endpoints []Endpoint) error {
	paths, schemaNames := buildOpenAPIPaths(endpoints)

	bw := bufio.NewWriter(w)
	const header = "# Generated by identuum-idp-oss/tools/api-docgen (--format=openapi).\n" +
		"# Do not hand-edit. To update, edit the // docgen: block above the relevant route registration and re-run the generator.\n"
	if _, err := bw.WriteString(header); err != nil {
		return err
	}
	if _, err := bw.WriteString("openapi: \"3.0.3\"\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("info:\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("  title: " + yamlScalar("identuum-idp-oss API") + "\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("  version: " + yamlScalar(version) + "\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("  description: " + yamlScalar("Machine-generated OpenAPI 3 specification for the identuum-idp-oss API surface. Generated by tools/api-docgen from // docgen: source annotations. Response bodies without a known schema record are described but not field-modeled; see the referenced Go symbol in identuum-idp-oss for the authoritative shape.") + "\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("paths:\n"); err != nil {
		return err
	}
	for i := range paths {
		if err := writeOpenAPIPathItem(bw, &paths[i]); err != nil {
			return fmt.Errorf("write path %s: %w", paths[i].Path, err)
		}
	}
	if err := writeOpenAPIComponents(bw, schemaNames); err != nil {
		return fmt.Errorf("write components: %w", err)
	}
	return bw.Flush()
}

// openAPIPathItem is one `paths.<path>` entry: the path string plus
// its ordered path parameters and ordered operations.
type openAPIPathItem struct {
	Path       string
	Params     []string
	Operations []openAPIOperation
}

// openAPIOperation is one HTTP-method operation under a path item.
type openAPIOperation struct {
	Method            string // lowercase: get, put, post, delete, patch
	OperationID       string
	Summary           string
	Tag               string
	SecuritySchemes   []string // ordered, deduplicated scheme names; nil = omit `security` (auth unknown)
	SecurityIsPublic  bool     // true => emit `security: []` (no auth required)
	ResponseSchemaRef string   // sanitized component name, or "" when the record carries no response_schema
	SuccessStatus     string   // HTTP status key for the success response ("200", "201", "204", …)
}

// canonicalMethodOrder is the conventional OpenAPI tooling order
// (Swagger UI / most generators) used so operations within a path
// item are emitted in a stable, tool-familiar sequence rather than
// raw HTTP-verb alphabetical order.
var canonicalMethodOrder = map[string]int{
	"get": 0, "put": 1, "post": 2, "delete": 3, "options": 4, "head": 5, "patch": 6, "trace": 7,
}

// buildOpenAPIPaths groups the (already-transformable) endpoint
// records into deterministic, sorted OpenAPI path items, and returns
// the sorted, deduplicated set of response-schema component names
// referenced by any operation.
func buildOpenAPIPaths(endpoints []Endpoint) ([]openAPIPathItem, []openAPISchemaComponent) {
	// Sort with generate()'s exact discipline first so that, for any
	// accidental (path, method) duplication, the first-sorted record
	// deterministically wins — matching the YAML emitter's own
	// stability guarantee.
	sorted := make([]Endpoint, len(endpoints))
	copy(sorted, endpoints)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].Module != sorted[j].Module {
			return sorted[i].Module < sorted[j].Module
		}
		if sorted[i].Surface != sorted[j].Surface {
			return sorted[i].Surface < sorted[j].Surface
		}
		if sorted[i].Path != sorted[j].Path {
			return sorted[i].Path < sorted[j].Path
		}
		if sorted[i].Method != sorted[j].Method {
			return sorted[i].Method < sorted[j].Method
		}
		return sorted[i].ID < sorted[j].ID
	})

	byPath := make(map[string]*openAPIPathItem, len(sorted))
	var pathOrder []string
	seenOps := make(map[string]bool, len(sorted)) // "<openapi-path> <method>" dedup guard
	schemaSet := make(map[string]string)          // sanitized component name -> original dotted record name

	for _, e := range sorted {
		oaPath, params := openAPIPathAndParams(e.Path)
		method := strings.ToLower(e.Method)
		opKey := oaPath + " " + method
		if seenOps[opKey] {
			continue // defensive: two records resolved to the identical (path, method); first wins.
		}
		seenOps[opKey] = true

		item, ok := byPath[oaPath]
		if !ok {
			item = &openAPIPathItem{Path: oaPath, Params: params}
			byPath[oaPath] = item
			pathOrder = append(pathOrder, oaPath)
		}

		op := openAPIOperation{
			Method:        method,
			OperationID:   e.ID,
			Summary:       e.Summary,
			Tag:           e.Surface,
			SuccessStatus: e.SuccessStatus,
		}
		schemes, isPublic, known := openAPISecurityForAuth(e.Auth)
		op.SecuritySchemes = schemes
		op.SecurityIsPublic = isPublic
		_ = known
		if e.ResponseSchema != "" {
			ref := sanitizeComponentName(e.ResponseSchema)
			op.ResponseSchemaRef = ref
			schemaSet[ref] = e.ResponseSchema
		}
		item.Operations = append(item.Operations, op)
	}

	sort.Strings(pathOrder)
	out := make([]openAPIPathItem, 0, len(pathOrder))
	for _, p := range pathOrder {
		item := byPath[p]
		sort.SliceStable(item.Operations, func(i, j int) bool {
			oi, oj := canonicalMethodOrder[item.Operations[i].Method], canonicalMethodOrder[item.Operations[j].Method]
			if oi != oj {
				return oi < oj
			}
			return item.Operations[i].Method < item.Operations[j].Method
		})
		out = append(out, *item)
	}

	schemaNames := make([]openAPISchemaComponent, 0, len(schemaSet))
	for sanitized, original := range schemaSet {
		schemaNames = append(schemaNames, openAPISchemaComponent{Name: sanitized, OriginalRecordName: original})
	}
	sort.Slice(schemaNames, func(i, j int) bool { return schemaNames[i].Name < schemaNames[j].Name })
	return out, schemaNames
}

// openAPISchemaComponent pairs a sanitized OpenAPI component name
// with the original dotted schema-record name it came from, so the
// component's description can cite the authoritative record without
// lossy un-sanitization.
type openAPISchemaComponent struct {
	Name               string
	OriginalRecordName string
}

// openAPIPathAndParams translates a gin-style path ("/api/v1/x/:id")
// into an OpenAPI 3 templated path ("/api/v1/x/{id}") and returns the
// ordered list of path parameter names found. OSS routes use only
// gin's ":name" segment form (confirmed: no "*" catch-all segments in
// the extracted registry) — no other translation is required.
func openAPIPathAndParams(ginPath string) (string, []string) {
	segments := strings.Split(ginPath, "/")
	var params []string
	for i, seg := range segments {
		if strings.HasPrefix(seg, ":") && len(seg) > 1 {
			name := seg[1:]
			segments[i] = "{" + name + "}"
			params = append(params, name)
		}
	}
	return strings.Join(segments, "/"), params
}

// openAPISecurityForAuth maps an Endpoint.Auth token (or "|"-joined
// set of alternatives — meaning "any one of these suffices") onto the
// security schemes declared in components.securitySchemes.
//
//   - "public"                                  -> (nil, true, true) — no auth required.
//   - "session" / "authenticated" / "site_admin" /
//     "org_admin"                               -> cookieAuth. All four are
//     the same underlying mechanism in OSS (a cookie-session-bound
//     Principal); the record's Auth string carries the effective ROLE
//     requirement in its own text, which OpenAPI's security object has
//     no field for — recording the same mechanism for all four is
//     accurate to the wire protocol without inventing a role/scope
//     concept the record doesn't express.
//   - "bearer"                                  -> bearerAuth.
//   - "oauth_client"                             -> oauthClientAuth.
//   - "unknown" / "" / anything else unrecognized -> (nil, false, false):
//     the operation omits `security` entirely rather than guessing.
func openAPISecurityForAuth(auth string) (schemes []string, isPublic bool, known bool) {
	auth = strings.TrimSpace(auth)
	if auth == "" || auth == "unknown" {
		return nil, false, false
	}
	if auth == "public" {
		return nil, true, true
	}
	seen := make(map[string]bool, 2)
	var out []string
	anyKnown := false
	for _, tok := range strings.Split(auth, "|") {
		var scheme string
		switch strings.TrimSpace(tok) {
		case "session", "authenticated", "site_admin", "org_admin":
			scheme = "cookieAuth"
		case "bearer":
			scheme = "bearerAuth"
		case "oauth_client":
			scheme = "oauthClientAuth"
		default:
			continue
		}
		anyKnown = true
		if !seen[scheme] {
			seen[scheme] = true
			out = append(out, scheme)
		}
	}
	if !anyKnown {
		return nil, false, false
	}
	return out, false, true
}

// sanitizeComponentName maps a dotted schema-record name
// (e.g. "oss.handlers.safeOrganization") onto an OpenAPI component
// name, which may not contain ".". The original dotted name is kept
// alongside (see openAPISchemaComponent) so no information is lost.
func sanitizeComponentName(name string) string {
	return strings.ReplaceAll(name, ".", "_")
}

func writeOpenAPIPathItem(bw *bufio.Writer, item *openAPIPathItem) error {
	if _, err := bw.WriteString("  " + yamlScalar(item.Path) + ":\n"); err != nil {
		return err
	}
	for i := range item.Operations {
		if err := writeOpenAPIOperation(bw, &item.Operations[i], item.Params); err != nil {
			return err
		}
	}
	return nil
}

func writeOpenAPIOperation(bw *bufio.Writer, op *openAPIOperation, params []string) error {
	if _, err := bw.WriteString("    " + op.Method + ":\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("      operationId: " + yamlScalar(op.OperationID) + "\n"); err != nil {
		return err
	}
	summary := op.Summary
	if summary == "" {
		summary = "(no summary recorded)"
	}
	if _, err := bw.WriteString("      summary: " + yamlScalar(summary) + "\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("      tags:\n        - " + yamlScalar(op.Tag) + "\n"); err != nil {
		return err
	}
	if len(params) > 0 {
		if _, err := bw.WriteString("      parameters:\n"); err != nil {
			return err
		}
		for _, p := range params {
			if _, err := bw.WriteString("        - name: " + yamlScalar(p) + "\n"); err != nil {
				return err
			}
			if _, err := bw.WriteString("          in: path\n          required: true\n          schema:\n            type: string\n"); err != nil {
				return err
			}
		}
	}
	if op.SecurityIsPublic {
		if _, err := bw.WriteString("      security: []\n"); err != nil {
			return err
		}
	} else if len(op.SecuritySchemes) > 0 {
		if _, err := bw.WriteString("      security:\n"); err != nil {
			return err
		}
		for _, s := range op.SecuritySchemes {
			if _, err := bw.WriteString("        - " + s + ": []\n"); err != nil {
				return err
			}
		}
	}
	if _, err := bw.WriteString("      responses:\n"); err != nil {
		return err
	}
	respDesc := summary
	// Success-response status key: the real code the handler writes
	// ("201" for a create, "204" for a no-content delete, …), sourced
	// from the record's SuccessStatus. Defaults to "200" defensively so
	// a record that somehow reached the emitter without a status still
	// produces a valid operation.
	status := op.SuccessStatus
	if status == "" {
		status = "200"
	}
	if _, err := bw.WriteString("        " + yamlScalar(status) + ":\n          description: " + yamlScalar(respDesc) + "\n"); err != nil {
		return err
	}
	// A 204 (and any other no-body success code) carries no response
	// schema, so the content block is emitted ONLY when the record
	// actually references a response schema — never fabricated.
	if op.ResponseSchemaRef != "" {
		if _, err := bw.WriteString("          content:\n            application/json:\n              schema:\n                $ref: " +
			yamlScalar("#/components/schemas/"+op.ResponseSchemaRef) + "\n"); err != nil {
			return err
		}
	}
	if _, err := bw.WriteString("        default:\n          description: " + yamlScalar("Error response — see identuum-idp-oss source for exact status/body per failure mode.") + "\n"); err != nil {
		return err
	}
	return nil
}

func writeOpenAPIComponents(bw *bufio.Writer, schemaNames []openAPISchemaComponent) error {
	if _, err := bw.WriteString("components:\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString("  securitySchemes:\n"); err != nil {
		return err
	}
	if _, err := bw.WriteString(
		"    bearerAuth:\n      type: http\n      scheme: bearer\n      bearerFormat: JWT\n" +
			"    cookieAuth:\n      type: apiKey\n      in: cookie\n      name: " + yamlScalar("identuum_session") +
			"\n      description: " + yamlScalar("Browser session cookie backing a cookie-authenticated Principal (site_admin, org_admin, or any authenticated user, depending on the operation's actual role requirement — see its summary).") + "\n" +
			"    oauthClientAuth:\n      type: http\n      scheme: basic\n      description: " +
			yamlScalar("OAuth 2.1 client authentication (client credentials / RFC 7592 management token) at client-management and token endpoints.") + "\n"); err != nil {
		return err
	}
	if len(schemaNames) == 0 {
		return nil
	}
	if _, err := bw.WriteString("  schemas:\n"); err != nil {
		return err
	}
	for _, s := range schemaNames {
		if _, err := bw.WriteString("    " + s.Name + ":\n      type: object\n      description: " +
			yamlScalar("Response shape defined by the OSS handler package (schema record: "+s.OriginalRecordName+"). Field-level shape is not modeled here — see the identuum-idp-oss Go source for the authoritative struct.") + "\n"); err != nil {
			return err
		}
	}
	return nil
}
