package tlscert

import (
	"crypto/x509"
	"encoding/pem"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/identuum/identuum-idp-oss/logger"
	"github.com/stretchr/testify/assert"
)

func init() {
	logger.InitializeZapLogger()
}

func TestGenerateAndLoadCertificate(t *testing.T) {
	certDir := "tls_certs"
	defer os.RemoveAll(certDir)

	// Clean before test just in case
	os.RemoveAll(certDir)

	GenerateSelfSignedCert("localhost", "identuum.com")

	certPath := filepath.Join(certDir, "tls_server.crt")
	keyPath := filepath.Join(certDir, "tls_server.key")

	assert.FileExists(t, certPath)
	assert.FileExists(t, keyPath)

	certBytes, err := os.ReadFile(certPath)
	assert.NoError(t, err)

	block, _ := pem.Decode(certBytes)
	assert.NotNil(t, block, "Failed to decode PEM block from cert")

	cert, err := x509.ParseCertificate(block.Bytes)
	assert.NoError(t, err)
	assert.Equal(t, "identuum.com", cert.Subject.Organization[0])
	assert.True(t, cert.NotAfter.After(time.Now()))

	// Calling again should hit the cache branch
	assert.NotPanics(t, func() {
		GenerateSelfSignedCert("localhost", "identuum.com")
	})
}

func TestGenerateCSR(t *testing.T) {
	certDir := "tls_certs"
	defer os.RemoveAll(certDir)
	os.RemoveAll(certDir)

	GenerateCSR("localhost", "identuum.com")

	csrPath := filepath.Join(certDir, "tls_server.csr")
	keyPath := filepath.Join(certDir, "tls_server.key")

	assert.FileExists(t, csrPath)
	assert.FileExists(t, keyPath)

	csrBytes, err := os.ReadFile(csrPath)
	assert.NoError(t, err)

	block, _ := pem.Decode(csrBytes)
	assert.NotNil(t, block)

	// Call again to hit the 'reuse existing key' branch
	assert.NotPanics(t, func() {
		GenerateCSR("localhost", "identuum.com")
	})
}

// §7.4 F1 — the RSA private key file MUST be written with owner-only (0600)
// permissions. The cert file remains 0644 (public). Pinning the stat-based
// invariant guards against a future regression of `writePrivatePEM` back to
// `os.Create` (which defaults to 0644 modulo umask and exposes the key to
// any user with filesystem reach into the tls_certs/ directory).
func TestGenerateSelfSignedCert_KeyFilePermissionsAre0600(t *testing.T) {
	certDir := "tls_certs"
	defer os.RemoveAll(certDir)
	os.RemoveAll(certDir)

	GenerateSelfSignedCert("localhost", "identuum.com")

	certPath := filepath.Join(certDir, "tls_server.crt")
	keyPath := filepath.Join(certDir, "tls_server.key")

	keyInfo, err := os.Stat(keyPath)
	assert.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), keyInfo.Mode().Perm(),
		"RSA private key file MUST be 0600 (owner read/write only) — world-readable keys defeat the point")

	// Cert file: public material, 0644 is the canonical shape.
	certInfo, err := os.Stat(certPath)
	assert.NoError(t, err)
	assert.Equal(t, os.FileMode(0644), certInfo.Mode().Perm(),
		"Certificate file should be 0644; narrower modes would break tooling that reads it as a non-owner user")
}

// §7.4 F1 — GenerateCSR writes its own RSA private key (if no existing one
// is present); that key must also be 0600. The CSR itself is public and
// stays at 0644.
func TestGenerateCSR_KeyFilePermissionsAre0600(t *testing.T) {
	certDir := "tls_certs"
	defer os.RemoveAll(certDir)
	os.RemoveAll(certDir)

	GenerateCSR("localhost", "identuum.com")

	csrPath := filepath.Join(certDir, "tls_server.csr")
	keyPath := filepath.Join(certDir, "tls_server.key")

	keyInfo, err := os.Stat(keyPath)
	assert.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), keyInfo.Mode().Perm(),
		"RSA private key generated by GenerateCSR MUST be 0600")

	csrInfo, err := os.Stat(csrPath)
	assert.NoError(t, err)
	assert.Equal(t, os.FileMode(0644), csrInfo.Mode().Perm(),
		"CSR file should be 0644; CSRs are public material")
}

// §7.4 F4 — two distinct self-signed cert generations must produce distinct
// 128-bit serial numbers. The previous hardcoded `big.NewInt(1)` made every
// generated cert share a serial, confusing trust-store rotation and breaking
// the uniqueness contract that X.509 consumers assume.
func TestGenerateSelfSignedCert_SerialIsRandom(t *testing.T) {
	certDir := "tls_certs"
	defer os.RemoveAll(certDir)

	parseSerial := func(t *testing.T) *x509.Certificate {
		t.Helper()
		certBytes, err := os.ReadFile(filepath.Join(certDir, "tls_server.crt"))
		assert.NoError(t, err)
		block, _ := pem.Decode(certBytes)
		assert.NotNil(t, block)
		parsed, err := x509.ParseCertificate(block.Bytes)
		assert.NoError(t, err)
		return parsed
	}

	os.RemoveAll(certDir)
	GenerateSelfSignedCert("localhost", "identuum.com")
	first := parseSerial(t)

	os.RemoveAll(certDir)
	GenerateSelfSignedCert("localhost", "identuum.com")
	second := parseSerial(t)

	assert.NotEqual(t, first.SerialNumber.String(), second.SerialNumber.String(),
		"distinct self-signed generations must produce distinct serial numbers")

	// Sanity: the new serials are meaningfully large (128-bit random values
	// have >> 1 as their typical magnitude; this pins that the hardcoded 1
	// has not crept back).
	assert.True(t, first.SerialNumber.BitLen() > 32,
		"serial should be a 128-bit random value, not a small constant; got bit length %d for first=%s",
		first.SerialNumber.BitLen(), first.SerialNumber.String())
}
