// Command notices writes and checks THIRD_PARTY_NOTICES: the licence of every
// Go module in ./cmd/identuum-idp's build list for the release targets
// (linux/amd64 and linux/arm64, united; standard library excluded) and
// of every npm package in the production closure of the embedded identuum-ui
// export's lockfile.
//
// The file records the two inputs it was generated from — a digest of the
// build list and the vendored identuum-ui commit — so `notices -check` (in
// verify and ci-verify) refuses a tree whose inputs moved without the file
// being regenerated. Regeneration (`notices -write`) needs the module cache
// and an identuum-ui checkout at the vendored commit; checking needs neither.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

// Component is one third-party component and its licence.
type Component struct {
	Ecosystem string // "go" or "npm"
	Name      string
	Version   string
	SPDX      string // an SPDX expression, or "UNKNOWN"
	Texts     []LicenseText
}

// LicenseText is one licence file shipped with a component.
type LicenseText struct {
	File string
	Text string
}

// Inputs are what the file is generated from.
type Inputs struct {
	BuildList []string // "path@version", sorted, unique
	UICommit  string
}

// BuildListDigest is the sha256 of the sorted build list, one entry per line.
func BuildListDigest(list []string) string {
	sum := sha256.Sum256([]byte(strings.Join(list, "\n") + "\n"))
	return hex.EncodeToString(sum[:])
}

const (
	headBuild = "build-list: sha256:"
	headUI    = "ui-commit: "
)

// Render writes the notices deterministically: the header, then the Go
// modules and the npm packages, each sorted by name and version.
func Render(in Inputs, comps []Component) string {
	sort.Slice(comps, func(i, j int) bool {
		a, b := comps[i], comps[j]
		if a.Ecosystem != b.Ecosystem {
			return a.Ecosystem < b.Ecosystem
		}
		if a.Name != b.Name {
			return a.Name < b.Name
		}
		return a.Version < b.Version
	})
	var b strings.Builder
	counts := map[string]int{}
	for _, c := range comps {
		counts[c.Ecosystem]++
	}
	fmt.Fprintln(&b, "THIRD-PARTY NOTICES — identuum-idp-oss")
	fmt.Fprintln(&b, "")
	fmt.Fprintln(&b, "identuum-idp-oss includes the third-party software below. Each component is")
	fmt.Fprintln(&b, "listed with its version, its licence (SPDX) and its licence text as shipped.")
	fmt.Fprintln(&b, "Generated by `go run ./tools/notices -write`; do not edit by hand.")
	fmt.Fprintln(&b, "")
	fmt.Fprintf(&b, "%s%s (%d Go modules of ./cmd/identuum-idp for %s, standard library excluded)\n", headBuild, BuildListDigest(in.BuildList), len(in.BuildList), strings.Join(releaseTargets, " and "))
	fmt.Fprintf(&b, "%s%s (identuum-ui; %d npm packages: its lockfile's production closure without host-specific native packages, and the packages vendored inside them)\n", headUI, in.UICommit, counts["npm"])
	for _, c := range comps {
		fmt.Fprintln(&b, "")
		fmt.Fprintln(&b, strings.Repeat("=", 78))
		fmt.Fprintf(&b, "%s %s %s\n", c.Ecosystem, c.Name, c.Version)
		fmt.Fprintf(&b, "License: %s\n", c.SPDX)
		if len(c.Texts) == 0 {
			fmt.Fprintln(&b, "(no licence file is shipped with this component)")
		}
		for _, t := range c.Texts {
			fmt.Fprintf(&b, "\n--- %s\n\n%s\n", t.File, strings.TrimRight(t.Text, "\n"))
		}
	}
	return b.String()
}

// Check compares the inputs a notices file was generated from with the
// current ones. It returns a one-line verdict and whether they agree.
func Check(file string, now Inputs) (string, bool) {
	var build, ui string
	for _, l := range strings.Split(file, "\n") {
		switch {
		case strings.HasPrefix(l, headBuild):
			build = strings.Fields(strings.TrimPrefix(l, headBuild))[0]
		case strings.HasPrefix(l, headUI):
			ui = strings.Fields(strings.TrimPrefix(l, headUI))[0]
		}
		if build != "" && ui != "" {
			break
		}
	}
	if build == "" || ui == "" {
		return "check FAILED: notices — THIRD_PARTY_NOTICES records no build-list digest or ui commit; regenerate it with `go run ./tools/notices -write`", false
	}
	var stale []string
	if want := BuildListDigest(now.BuildList); build != want {
		stale = append(stale, fmt.Sprintf("the build list changed (file sha256:%s, now sha256:%s over %d modules)", build, want, len(now.BuildList)))
	}
	if ui != now.UICommit {
		stale = append(stale, fmt.Sprintf("the vendored identuum-ui commit changed (file %s, now %s)", ui, now.UICommit))
	}
	if len(stale) > 0 {
		return "check FAILED: notices — " + strings.Join(stale, "; ") + "; regenerate THIRD_PARTY_NOTICES with `go run ./tools/notices -write`", false
	}
	return fmt.Sprintf("check OK: notices THIRD_PARTY_NOTICES matches the build list (%d Go modules) and identuum-ui %s", len(now.BuildList), shortSHA(now.UICommit)), true
}

func shortSHA(s string) string {
	if len(s) > 12 {
		return s[:12]
	}
	return s
}
