package service

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"strings"

	"github.com/google/uuid"

	"github.com/identuum/identuum-idp-oss/internal/domain"
	"github.com/identuum/identuum-idp-oss/internal/lifecycle"
	"github.com/identuum/identuum-idp-oss/internal/repository"
)

// SecretCipher is the minimal encrypt/decrypt seam this service needs to
// protect an OIDC provider's client_secret at rest. *crypto.CryptoService
// satisfies it (the same AES-256-GCM, env-keyed cipher that protects MFA
// secrets). A nil cipher is fail-closed at construction (P-018 fatal
// fault): the service never stores or returns a plaintext secret.
type SecretCipher interface {
	Encrypt(plaintext string) (string, error)
	Decrypt(ciphertext string) (string, error)
}

// OIDCProviderConfigService manages an organization's SINGLE upstream OIDC
// identity provider — Slice 1 of docs/design/oss-basic-oidc-login.md. It is
// the OSS/CE tripwire for basic single-provider login:
//
//   - TYPE is oidc ONLY. ldap/ad are CE transports and are refused here.
//   - At most ONE oidc provider per org. A second is refused at this
//     service layer. The schema's UNIQUE(organization_id, type, priority)
//     would permit several via distinct priorities, so one-per-org is a
//     CODE rule, not a DB constraint — this is the load-bearing guardrail
//     against multi-IdP (managed federation) drift, which is CE.
//   - client_secret is encrypted at rest via SecretCipher, decrypted only
//     in memory, and never logged or returned in plaintext.
//
// There is NO HTTP surface here (the org-admin config API is Slice 2) and
// there is NO multi-IdP surface, ever (that is CE). New provider row IDs
// are UUIDv7 generated by the identity_providers DEFAULT uuidv7() column
// via the existing repository Create — the service does not set the ID.
type OIDCProviderConfigService struct {
	repo   repository.IdentityProviderRepository
	cipher SecretCipher
}

// NewOIDCProviderConfigService constructs the service. repo and cipher must
// be non-nil; a nil dependency records a fatal startup fault (P-018,
// NOT-SERVING) rather than panicking, so the process stays alive and
// surfaces the fault instead of crashing a serving path.
func NewOIDCProviderConfigService(report *lifecycle.StartupReport, repo repository.IdentityProviderRepository, cipher SecretCipher) *OIDCProviderConfigService {
	if repo == nil {
		report.Fatal("NewOIDCProviderConfigService", "service: NewOIDCProviderConfigService requires a non-nil IdentityProviderRepository")
	}
	if cipher == nil {
		report.Fatal("NewOIDCProviderConfigService", "service: NewOIDCProviderConfigService requires a non-nil SecretCipher (client_secret must never be stored in plaintext)")
	}
	return &OIDCProviderConfigService{repo: repo, cipher: cipher}
}

var errOIDCProviderExists = errors.New("service: an OIDC provider already exists for this organization (one per organization)")

// ErrOIDCProviderExists is returned when an org already has an oidc
// provider and a second create is attempted. A handler maps it to 409.
func ErrOIDCProviderExists() error { return errOIDCProviderExists }

var errUnsupportedProviderType = errors.New("service: unsupported identity-provider type — OSS basic login supports oidc only (ldap/ad are CE)")

// ErrUnsupportedProviderType is returned when a non-oidc type is supplied.
// A handler maps it to 400. It is the type half of the OSS/CE tripwire.
func ErrUnsupportedProviderType() error { return errUnsupportedProviderType }

var errInvalidIssuerURL = errors.New("service: invalid OIDC issuer/discovery URL — must be a well-formed absolute https URL")

// ErrInvalidIssuerURL is returned when the issuer/discovery URL is not a
// well-formed absolute https URL. Structural validation only — no network
// fetch happens in this slice (that is Slice 3).
func ErrInvalidIssuerURL() error { return errInvalidIssuerURL }

var errOIDCProviderNotFound = errors.New("service: no OIDC provider configured for this organization")

// ErrOIDCProviderNotFound is returned by Get/Delete when the org has no
// configured oidc provider. A handler maps it to 404.
func ErrOIDCProviderNotFound() error { return errOIDCProviderNotFound }

var errOIDCProviderInvalidInput = errors.New("service: invalid OIDC provider configuration")

// ErrOIDCProviderInvalidInput is returned for missing required fields
// (organization, name, client_id). A handler maps it to 400.
func ErrOIDCProviderInvalidInput() error { return errOIDCProviderInvalidInput }

// OIDCProviderInput is the create shape. Type carries the caller's
// requested provider type so the OSS boundary can refuse anything but
// oidc. ClientSecret is PLAINTEXT input; it is encrypted before
// persistence and is never stored or returned in the clear. An empty
// ClientSecret is allowed (public / PKCE-only clients); a non-empty one is
// encrypted via SecretCipher.
type OIDCProviderInput struct {
	OrganizationID       uuid.UUID
	Type                 domain.IdentityProviderType
	Name                 string
	Slug                 string
	IssuerURL            string
	ClientID             string
	ClientSecret         string
	Scopes               []string
	RedirectURIs         []string
	EmailDomains         []string
	ClaimMapping         map[string]string
	AttributeMapping     map[string]string
	PKCERequired         bool
	AllowExternalDomains bool
}

// CreateOIDCProvider validates the input, enforces type=oidc-only and
// one-oidc-provider-per-org, encrypts the client_secret at rest, and
// persists the provider. The returned provider carries the encrypted
// secret only — the plaintext is never persisted or returned.
func (s *OIDCProviderConfigService) CreateOIDCProvider(ctx context.Context, in OIDCProviderInput) (*domain.IdentityProvider, error) {
	if err := validateOIDCInput(in); err != nil {
		return nil, err
	}

	// One-per-org tripwire: refuse a second oidc provider for this org.
	existing, err := s.existingOIDCProvider(ctx, in.OrganizationID)
	if err != nil {
		return nil, err
	}
	if existing != nil {
		return nil, errOIDCProviderExists
	}

	// Encrypt the client_secret at rest. Empty ⇒ public/PKCE-only client:
	// store empty rather than an encryption of "".
	encryptedSecret := ""
	if in.ClientSecret != "" {
		encryptedSecret, err = s.cipher.Encrypt(in.ClientSecret)
		if err != nil {
			return nil, fmt.Errorf("service: failed to encrypt client_secret: %w", err)
		}
	}

	slug := strings.TrimSpace(in.Slug)
	if slug == "" {
		slug = "oidc"
	}

	provider := &domain.IdentityProvider{
		OrganizationID: in.OrganizationID,
		Type:           domain.IDPTypeOIDC,
		Name:           strings.TrimSpace(in.Name),
		Slug:           slug,
		Priority:       0, // single provider — priority is unused in OSS
		Active:         true,
		Config: domain.ProviderConfig{
			IssuerURL:             strings.TrimSpace(in.IssuerURL),
			ClientID:              strings.TrimSpace(in.ClientID),
			ClientSecretEncrypted: encryptedSecret,
			Scopes:                in.Scopes,
			RedirectURIs:          in.RedirectURIs,
			EmailDomains:          in.EmailDomains,
			ClaimMapping:          in.ClaimMapping,
			AttributeMapping:      in.AttributeMapping,
			PKCERequired:          in.PKCERequired,
			AllowExternalDomains:  in.AllowExternalDomains,
		},
	}

	// The repository INSERT omits id, so the identity_providers
	// DEFAULT uuidv7() assigns a UUIDv7 and RETURNING id reads it back.
	return s.repo.Create(ctx, provider)
}

// GetOIDCProvider returns the organization's single oidc provider, or
// ErrOIDCProviderNotFound when none is configured. The returned provider's
// client_secret stays encrypted; callers needing the plaintext use
// DecryptClientSecret.
func (s *OIDCProviderConfigService) GetOIDCProvider(ctx context.Context, orgID uuid.UUID) (*domain.IdentityProvider, error) {
	provider, err := s.existingOIDCProvider(ctx, orgID)
	if err != nil {
		return nil, err
	}
	if provider == nil {
		return nil, errOIDCProviderNotFound
	}
	return provider, nil
}

// UpdateOIDCProvider updates the organization's single oidc provider.
// Invariants held: type stays oidc (a non-oidc input Type is refused), the
// issuer/discovery URL is re-validated (structural https, no network), and
// the update targets the org's ONE existing provider (one-per-org). The
// client_secret is re-encrypted ONLY when a new plaintext is supplied;
// an empty ClientSecret preserves the stored ciphertext (so callers can
// edit other fields without resubmitting the secret). The provider ID,
// organization, priority, and active flag are preserved from the stored row.
func (s *OIDCProviderConfigService) UpdateOIDCProvider(ctx context.Context, orgID uuid.UUID, in OIDCProviderInput) (*domain.IdentityProvider, error) {
	if in.Type != domain.IDPTypeOIDC {
		return nil, errUnsupportedProviderType
	}
	if err := validateIssuerURL(in.IssuerURL); err != nil {
		return nil, err
	}
	if strings.TrimSpace(in.Name) == "" || strings.TrimSpace(in.ClientID) == "" {
		return nil, errOIDCProviderInvalidInput
	}

	existing, err := s.existingOIDCProvider(ctx, orgID)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, errOIDCProviderNotFound
	}

	// Preserve the stored ciphertext unless a new plaintext secret is given.
	encryptedSecret := existing.Config.ClientSecretEncrypted
	if in.ClientSecret != "" {
		encryptedSecret, err = s.cipher.Encrypt(in.ClientSecret)
		if err != nil {
			return nil, fmt.Errorf("service: failed to encrypt client_secret: %w", err)
		}
	}

	slug := strings.TrimSpace(in.Slug)
	if slug == "" {
		slug = existing.Slug
	}

	updated := &domain.IdentityProvider{
		ID:             existing.ID,
		OrganizationID: existing.OrganizationID,
		Type:           domain.IDPTypeOIDC,
		Name:           strings.TrimSpace(in.Name),
		Slug:           slug,
		Priority:       existing.Priority,
		Active:         existing.Active,
		Config: domain.ProviderConfig{
			IssuerURL:             strings.TrimSpace(in.IssuerURL),
			ClientID:              strings.TrimSpace(in.ClientID),
			ClientSecretEncrypted: encryptedSecret,
			Scopes:                in.Scopes,
			RedirectURIs:          in.RedirectURIs,
			EmailDomains:          in.EmailDomains,
			ClaimMapping:          in.ClaimMapping,
			AttributeMapping:      in.AttributeMapping,
			PKCERequired:          in.PKCERequired,
			AllowExternalDomains:  in.AllowExternalDomains,
		},
	}

	return s.repo.Update(ctx, updated)
}

// DeleteOIDCProvider removes the org's oidc provider by id, scoped to the
// organization. Returns ErrOIDCProviderNotFound when nothing was removed.
func (s *OIDCProviderConfigService) DeleteOIDCProvider(ctx context.Context, orgID, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id, orgID); err != nil {
		return errOIDCProviderNotFound
	}
	return nil
}

// DecryptClientSecret returns the in-memory plaintext client_secret for the
// provider. It is the only path that reveals the secret; the plaintext is
// never persisted, logged, or returned by Get. An empty stored secret
// (public/PKCE-only client) yields an empty string with no error.
func (s *OIDCProviderConfigService) DecryptClientSecret(provider *domain.IdentityProvider) (string, error) {
	if provider == nil {
		return "", errOIDCProviderNotFound
	}
	if provider.Config.ClientSecretEncrypted == "" {
		return "", nil
	}
	return s.cipher.Decrypt(provider.Config.ClientSecretEncrypted)
}

// existingOIDCProvider returns the org's oidc provider if one exists, or
// (nil, nil) when none does. It filters ListByOrganization by type rather
// than using GetByOrgAndType, whose not-found is signalled by a
// non-sentinel error that cannot be told apart from a real failure.
func (s *OIDCProviderConfigService) existingOIDCProvider(ctx context.Context, orgID uuid.UUID) (*domain.IdentityProvider, error) {
	providers, err := s.repo.ListByOrganization(ctx, orgID)
	if err != nil {
		return nil, fmt.Errorf("service: failed to list identity providers: %w", err)
	}
	for _, p := range providers {
		if p != nil && p.Type == domain.IDPTypeOIDC {
			return p, nil
		}
	}
	return nil, nil
}

// validateOIDCInput enforces the required fields, the oidc-only type rule,
// and structural (non-network) issuer/discovery URL validation.
func validateOIDCInput(in OIDCProviderInput) error {
	if in.Type != domain.IDPTypeOIDC {
		return errUnsupportedProviderType
	}
	if in.OrganizationID == uuid.Nil {
		return errOIDCProviderInvalidInput
	}
	if strings.TrimSpace(in.Name) == "" {
		return errOIDCProviderInvalidInput
	}
	if strings.TrimSpace(in.ClientID) == "" {
		return errOIDCProviderInvalidInput
	}
	return validateIssuerURL(in.IssuerURL)
}

// validateIssuerURL checks the issuer/discovery URL is a well-formed
// absolute https URL. Structural only — no network fetch (Slice 3).
func validateIssuerURL(raw string) error {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return errInvalidIssuerURL
	}
	u, err := url.Parse(trimmed)
	if err != nil {
		return errInvalidIssuerURL
	}
	if u.Scheme != "https" || u.Host == "" {
		return errInvalidIssuerURL
	}
	return nil
}
